#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm eslint
pnpm prettier
pnpm test

echo ""
echo "---------------------------"
echo "|Success - Welcome to push|"
echo "---------------------------"
echo ""
